### ISSUE TITLE
Add mixpanel event for when users use the edit diagram link

### ISSUE THREAD

**Issue by bra1nDump** [bra1nDump/show-me-chatgpt-plugin#12]
Would be nice if we knew if people were actually attempting edits to the diagram outside of chatgpt to see if this functionality is desired before we further iterate on it

**Comment by jemsystemsIT** [comment]
Would be nice if we knew if people were actually attempting edits to the diagram outside of chatgpt to see if this functionality is desired before we further iterate on it

**Comment by bra1nDump** [comment]
#37
